export type Lang = "en" | "ml";

export const copy = {
  en: {
    appName: "RationLens",
    citizen: "Citizen",
    shopkeeper: "Shopkeeper",
    language: "Language",
    findShop: "Find my ration shop",
    imShopkeeper: "I'm a shopkeeper",
    landingTitle: "See stock before you travel",
    landingBody:
      "Check rice, wheat, and sugar at nearby ration shops. Updates come from the shopkeeper, not from a guess.",
    searchPlaceholder: "Ask in English or Malayalam",
    search: "Search",
    understood: "Understood: Rice · Nearby",
    list: "List",
    map: "Map",
    viewShop: "View shop",
    away: "away",
    getDirections: "Get directions",
    notifyMe: "Notify me",
    notified: "You'll be notified",
    notifications: "Notifications",
    noNotifications: "No notifications yet.",
    noNotificationsBody:
      "When an item you asked about comes back, the message will appear here.",
    login: "Log in",
    signup: "Create account",
    email: "Email",
    password: "Password",
    name: "Your name",
    role: "I am",
    assignedShop: "My shop",
    loginError: "That email or password is not right. Try the demo login on this page.",
    demoHint: "Demo: citizen@demo.com or shopkeeper@demo.com, password demo123",
    nearbyShops: "Nearby shops",
    shopNotFound: "This shop is not on the list.",
    checkNumbers:
      "Check these numbers. Change any that are wrong. Stock does not change until you confirm.",
    choosePhoto:
      "Choose a photo of the stock register. You can edit the numbers before they go live.",
    showEmpty: "Show empty list",
    showList: "Show sample messages",
    saveUpdate: "Save Update",
    saved: "Stock update saved.",
    history: "History",
    updatePhoto: "Update via photo",
    manualUpdate: "Update stock",
    quantity: "Quantity",
    confirmPublish: "Confirm and publish",
    retake: "Retake image",
    enterManually: "Enter manually instead",
    uploadImage: "Upload image",
    weDetected: "We detected",
    reading: "Reading the photo…",
    published: "Published. Stock changed only after you confirmed.",
    back: "Back",
  },
  ml: {
    appName: "റേഷൻലെൻസ്",
    citizen: "പൗരൻ",
    shopkeeper: "കടയുടമ",
    language: "ഭാഷ",
    findShop: "എന്റെ റേഷൻ കട കണ്ടെത്തുക",
    imShopkeeper: "ഞാൻ ഒരു കടയുടമയാണ്",
    landingTitle: "പോകുന്നതിന് മുമ്പ് സ്റ്റോക്ക് കാണുക",
    landingBody:
      "അടുത്തുള്ള റേഷൻ കടകളിലെ അരി, ഗോതമ്പ്, പഞ്ചസാര. അപ്‌ഡേറ്റ് കടയുടമയിൽ നിന്നാണ്, ഊഹത്തിൽ നിന്നല്ല.",
    searchPlaceholder: "ഇംഗ്ലീഷിലോ മലയാളത്തിലോ ചോദിക്കുക",
    search: "തിരയുക",
    understood: "മനസ്സിലായി: അരി · അടുത്തുള്ളത്",
    list: "പട്ടിക",
    map: "ഭൂപടം",
    viewShop: "കട കാണുക",
    away: "ദൂരെ",
    getDirections: "വഴി കാണുക",
    notifyMe: "അറിയിക്കുക",
    notified: "നിങ്ങളെ അറിയിക്കും",
    notifications: "അറിയിപ്പുകൾ",
    noNotifications: "ഇതുവരെ അറിയിപ്പുകളില്ല.",
    noNotificationsBody:
      "നിങ്ങൾ ചോദിച്ച സാധനം വന്നാൽ സന്ദേശം ഇവിടെ കാണാം.",
    login: "ലോഗിൻ",
    signup: "അക്കൗണ്ട് ഉണ്ടാക്കുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    name: "പേര്",
    role: "ഞാൻ ഒരു",
    assignedShop: "എന്റെ കട",
    loginError: "ഇമെയിലോ പാസ്‌വേഡോ ശരിയല്ല. ഈ പേജിലെ ഡെമോ ലോഗിൻ പരീക്ഷിക്കുക.",
    demoHint: "ഡെമോ: citizen@demo.com അല്ലെങ്കിൽ shopkeeper@demo.com, പാസ്‌വേഡ് demo123",
    nearbyShops: "അടുത്തുള്ള കടകൾ",
    shopNotFound: "ഈ കട പട്ടികയിലില്ല.",
    checkNumbers:
      "ഈ അക്കങ്ങൾ പരിശോധിക്കുക. തെറ്റുള്ളത് മാറ്റുക. നിങ്ങൾ സ്ഥിരീകരിക്കും വരെ സ്റ്റോക്ക് മാറില്ല.",
    choosePhoto:
      "സ്റ്റോക്ക് രജിസ്റ്ററിന്റെ ഫോട്ടോ തിരഞ്ഞെടുക്കുക. ലൈവാകുന്നതിന് മുമ്പ് അക്കങ്ങൾ തിരുത്താം.",
    showEmpty: "ശൂന്യമായ പട്ടിക കാണിക്കുക",
    showList: "മാതൃക സന്ദേശങ്ങൾ കാണിക്കുക",
    saveUpdate: "അപ്‌ഡേറ്റ് സേവ് ചെയ്യുക",
    saved: "സ്റ്റോക്ക് അപ്‌ഡേറ്റ് സേവ് ചെയ്തു.",
    history: "ചരിത്രം",
    updatePhoto: "ഫോട്ടോ വഴി അപ്‌ഡേറ്റ്",
    manualUpdate: "സ്റ്റോക്ക് അപ്‌ഡേറ്റ്",
    quantity: "അളവ്",
    confirmPublish: "സ്ഥിരീകരിച്ച് പ്രസിദ്ധീകരിക്കുക",
    retake: "വീണ്ടും ഫോട്ടോ",
    enterManually: "തന്നെ നൽകുക",
    uploadImage: "ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    weDetected: "കണ്ടെത്തിയത്",
    reading: "ചിത്രം വായിക്കുന്നു…",
    published: "പ്രസിദ്ധീകരിച്ചു. നിങ്ങൾ സ്ഥിരീകരിച്ചതിന് ശേഷം മാത്രം സ്റ്റോക്ക് മാറി.",
    back: "തിരികെ",
  },
} as const;
