export type Lang = "en" | "ml";

export const copy = {
  en: {
    appName: "RationLens",
    citizen: "Citizen",
    shopkeeper: "Shopkeeper",
    language: "Language",
    findShop: "Find my ration shop",
    imShopkeeper: "I'm a shopkeeper",
    landingTitle: "See stock before you travel",
    landingBody:
      "Check rice, wheat, and sugar at nearby ration shops. Updates come from the shopkeeper, not from a guess.",
    searchPlaceholder: "Ask in English or Malayalam",
    search: "Search",
    voiceControls: "Voice controls",
    voiceSearch: "Ask by voice",
    stopListening: "Stop listening",
    speakResults: "Read results aloud",
    stopSpeaking: "Stop reading",
    voiceUnsupported: "Voice controls are not supported in this browser.",
    searchInterpreted: "Search interpreted as",
    shopSearch: "Shop search",
    noMatchingStock: "No matching shop or stock found.",
    understood: "Understood: Rice · Nearby",
    list: "List",
    map: "Map",
    viewShop: "View shop",
    away: "away",
    findingLocation: "Finding your location…",
    approximateLocation: "Using an approximate location.",
    tryAgain: "Try again",
    dismiss: "Dismiss",
    getDirections: "Get directions",
    notifyMe: "Notify me",
    notified: "You'll be notified",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    noHistory: "No history yet",
    noNotificationsBody:
      "When an item you asked about comes back, the message will appear here.",
    login: "Log in",
    signup: "Create account",
    email: "Email",
    password: "Password",
    name: "Your name",
    role: "I am",
    assignedShop: "My shop",
    loginError: "That email or password is not right.",
    checkEmail: "Check your email to confirm your account",
    nearbyShops: "Nearby shops",
    shopNotFound: "This shop is not on the list.",
    checkNumbers:
      "Check these numbers. Change any that are wrong. Stock does not change until you confirm.",
    choosePhoto:
      "Choose a photo of the stock register. You can edit the numbers before they go live.",
    showEmpty: "Show empty list",
    showList: "Show sample messages",
    saveUpdate: "Save update",
    stockSection: "Current stock",
    saved: "Stock update saved.",
    history: "History",
    viewRequests: "View requests",
    noRequests: "No pending requests right now.",
    waiting: "waiting",
    requested: "Requested",
    updatePhoto: "Update via photo",
    manualUpdate: "Update stock",
    quantity: "Quantity",
    confirmPublish: "Confirm and publish",
    retake: "Retake image",
    enterManually: "Enter manually instead",
    uploadImage: "Upload image",
    weDetected: "We detected",
    reading: "Reading the photo…",
    published: "Published. Stock changed only after you confirmed.",
    back: "Back",
  },
  ml: {
    appName: "റേഷൻലെൻസ്",
    citizen: "പൗരൻ",
    shopkeeper: "കടയുടമ",
    language: "ഭാഷ",
    findShop: "എന്റെ റേഷൻ കട കണ്ടെത്തുക",
    imShopkeeper: "ഞാൻ ഒരു കടയുടമയാണ്",
    landingTitle: "പോകുന്നതിന് മുമ്പ് സ്റ്റോക്ക് കാണുക",
    landingBody:
      "അടുത്തുള്ള റേഷൻ കടകളിലെ അരി, ഗോതമ്പ്, പഞ്ചസാര. അപ്‌ഡേറ്റ് കടയുടമയിൽ നിന്നാണ്, ഊഹത്തിൽ നിന്നല്ല.",
    searchPlaceholder: "ഇംഗ്ലീഷിലോ മലയാളത്തിലോ ചോദിക്കുക",
    search: "തിരയുക",
    voiceControls: "ശബ്ദ നിയന്ത്രണങ്ങൾ",
    voiceSearch: "ശബ്ദത്തിൽ ചോദിക്കുക",
    stopListening: "കേൾക്കുന്നത് നിർത്തുക",
    speakResults: "ഫലങ്ങൾ ശബ്ദത്തിൽ കേൾക്കുക",
    stopSpeaking: "വായന നിർത്തുക",
    voiceUnsupported: "ഈ ബ്രൗസറിൽ ശബ്ദ സൗകര്യം ലഭ്യമല്ല.",
    searchInterpreted: "തിരച്ചിൽ മനസ്സിലാക്കിയത്",
    shopSearch: "കട തിരച്ചിൽ",
    noMatchingStock: "പൊരുത്തപ്പെടുന്ന കടയോ സ്റ്റോക്കോ കണ്ടെത്തിയില്ല.",
    understood: "മനസ്സിലായി: അരി · അടുത്തുള്ളത്",
    list: "പട്ടിക",
    map: "ഭൂപടം",
    viewShop: "കട കാണുക",
    away: "ദൂരെ",
    findingLocation: "നിങ്ങളുടെ സ്ഥലം കണ്ടെത്തുന്നു…",
    approximateLocation: "ഏകദേശ സ്ഥലമാണ് ഉപയോഗിക്കുന്നത്.",
    tryAgain: "വീണ്ടും ശ്രമിക്കുക",
    dismiss: "ഒഴിവാക്കുക",
    getDirections: "വഴി കാണുക",
    notifyMe: "അറിയിക്കുക",
    notified: "നിങ്ങളെ അറിയിക്കും",
    notifications: "അറിയിപ്പുകൾ",
    noNotifications: "ഇതുവരെ അറിയിപ്പുകളില്ല",
    noHistory: "ചരിത്രമൊന്നുമില്ല",
    noNotificationsBody:
      "നിങ്ങൾ ചോദിച്ച സാധനം വന്നാൽ സന്ദേശം ഇവിടെ കാണാം.",
    login: "ലോഗിൻ",
    signup: "അക്കൗണ്ട് ഉണ്ടാക്കുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    name: "പേര്",
    role: "ഞാൻ ഒരു",
    assignedShop: "എന്റെ കട",
    loginError: "ഇമെയിലോ പാസ്‌വേഡോ ശരിയല്ല.",
    checkEmail: "അക്കൗണ്ട് സ്ഥിരീകരിക്കാൻ ഇമെയിൽ പരിശോധിക്കുക",
    nearbyShops: "അടുത്തുള്ള കടകൾ",
    shopNotFound: "ഈ കട പട്ടികയിലില്ല.",
    checkNumbers:
      "ഈ അക്കങ്ങൾ പരിശോധിക്കുക. തെറ്റുള്ളത് മാറ്റുക. നിങ്ങൾ സ്ഥിരീകരിക്കും വരെ സ്റ്റോക്ക് മാറില്ല.",
    choosePhoto:
      "സ്റ്റോക്ക് രജിസ്റ്ററിന്റെ ഫോട്ടോ തിരഞ്ഞെടുക്കുക. ലൈവാകുന്നതിന് മുമ്പ് അക്കങ്ങൾ തിരുത്താം.",
    showEmpty: "ശൂന്യമായ പട്ടിക കാണിക്കുക",
    showList: "മാതൃക സന്ദേശങ്ങൾ കാണിക്കുക",
    saveUpdate: "അപ്‌ഡേറ്റ് സേവ് ചെയ്യുക",
    stockSection: "നിലവിലെ സ്റ്റോക്ക്",
    saved: "സ്റ്റോക്ക് അപ്‌ഡേറ്റ് സേവ് ചെയ്തു.",
    history: "ചരിത്രം",
    viewRequests: "അഭ്യർത്ഥനകൾ കാണുക",
    noRequests: "ഇപ്പോൾ തീർച്ചപ്പെടുത്താത്ത അഭ്യർത്ഥനകളില്ല.",
    waiting: "കാത്തിരിക്കുന്നു",
    requested: "അഭ്യർത്ഥിച്ചത്",
    updatePhoto: "ഫോട്ടോ വഴി അപ്‌ഡേറ്റ്",
    manualUpdate: "സ്റ്റോക്ക് അപ്‌ഡേറ്റ്",
    quantity: "അളവ്",
    confirmPublish: "സ്ഥിരീകരിച്ച് പ്രസിദ്ധീകരിക്കുക",
    retake: "വീണ്ടും ഫോട്ടോ",
    enterManually: "തന്നെ നൽകുക",
    uploadImage: "ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    weDetected: "കണ്ടെത്തിയത്",
    reading: "ചിത്രം വായിക്കുന്നു…",
    published: "പ്രസിദ്ധീകരിച്ചു. നിങ്ങൾ സ്ഥിരീകരിച്ചതിന് ശേഷം മാത്രം സ്റ്റോക്ക് മാറി.",
    back: "തിരികെ",
  },
} as const;
