export type Lang = "en" | "ml";

export const copy = {
  en: {
    appName: "RationLens",
    citizen: "Citizen",
    shopkeeper: "Shopkeeper",
    language: "Language",
    findShop: "Find my ration shop",
    imShopkeeper: "I'm a shopkeeper",
    landingTitle: "See stock before you travel",
    landingBody:
      "Check rice, wheat, and sugar at nearby ration shops. Updates come from the shopkeeper, not from a guess.",
    searchPlaceholder: "Ask in English or Malayalam",
    search: "Search",
    voiceControls: "Voice controls",
    voiceSearch: "Ask by voice",
    stopListening: "Stop listening",
    speakResults: "Read results aloud",
    stopSpeaking: "Stop reading",
    voiceUnsupported: "Voice controls are not supported in this browser.",
    searchInterpreted: "Search interpreted as",
    shopSearch: "Shop search",
    noMatchingStock: "No matching shop or stock found.",
    understood: "Understood: Rice · Nearby",
    list: "List",
    map: "Map",
    viewShop: "View shop",
    away: "away",
    findingLocation: "Finding your location…",
    approximateLocation: "Using an approximate location.",
    tryAgain: "Try again",
    dismiss: "Dismiss",
    getDirections: "Get directions",
    notifyMe: "Notify me",
    notified: "You'll be notified",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    noHistory: "No history yet",
    noNotificationsBody:
      "When an item you asked about comes back, the message will appear here.",
    login: "Log in",
    signup: "Create account",
    email: "Email",
    password: "Password",
    name: "Your name",
    role: "I am",
    assignedShop: "My shop",
    loginError: "That email or password is not right.",
    checkEmail: "Check your email to confirm your account",
    nearbyShops: "Nearby shops",
    shopNotFound: "This shop is not on the list.",
    checkNumbers:
      "Check these numbers. Change any that are wrong. Stock does not change until you confirm.",
    choosePhoto:
      "Choose a photo of the stock register. You can edit the numbers before they go live.",
    showEmpty: "Show empty list",
    showList: "Show sample messages",
    saveUpdate: "Save update",
    stockSection: "Current stock",
    saved: "Stock update saved.",
    history: "History",
    viewRequests: "View requests",
    noRequests: "No pending requests right now.",
    waiting: "waiting",
    requested: "Requested",
    updatePhoto: "Update via photo",
    manualUpdate: "Update stock",
    quantity: "Quantity",
    confirmPublish: "Confirm and publish",
    retake: "Retake image",
    enterManually: "Enter manually instead",
    uploadImage: "Upload image",
    weDetected: "We detected",
    reading: "Reading the photo…",
    published: "Published. Stock changed only after you confirmed.",
    back: "Back",
    rightsTitle: "Know Your Rights",
    rightsIntro: "Select your ration card color to see your monthly entitlement.",
    selectCardColor: "Select your card color",
    riceEntitlement: "Rice",
    wheatEntitlement: "Wheat / Atta",
    keroseneEntitlement: "Kerosene",
    readRights: "Read aloud",
    pendingVerificationTitle: "Verification pending",
    pendingVerificationBody: "Your shopkeeper account is awaiting verification. An admin will review it shortly.",
    rejectedTitle: "Verification rejected",
    rejectedBody: "Your application was not approved. Please contact support.",
    licenseNumber: "FPS License Number",
    phoneNumber: "Phone Number",
    uploadLicensePhoto: "Photo of your displayed shop license",
    applicationSubmitted: "Your application is under review. You'll be notified once approved.",
    approve: "Approve",
    reject: "Reject",
    adminShopkeeperQueue: "Shopkeeper Queue",
    logout: "Log out",
    shopkeeperQueueTitle: "Shopkeeper Queue",
    noPendingApplications: "No pending shopkeeper applications.",
    phoneLabel: "Phone",
    licenseLabel: "License",
    noProofImage: "No proof image provided",
    assignShop: "Assign Shop",
    selectAShop: "Select a shop...",
    approvalFailed: "Approval failed.",
    rejectionFailed: "Rejection failed.",
    confirmReject: "Are you sure you want to reject this applicant?",
    unknownName: "Unknown Name",
    noMalayalamVoice: "No Malayalam voice found on this device — try a different browser or device, or read the text directly.",
    reportIssue: "Report an issue",
    complaintCategory: "What's the issue?",
    categoryOvercharging: "Overcharging",
    categoryWrongStock: "Wrong stock shown",
    categoryBehavior: "Staff behavior",
    categoryOther: "Other",
    complaintDescription: "Add details (optional)",
    submitComplaint: "Submit report",
    complaintSubmitted: "Thank you. Your report has been sent to the admin.",
    adminComplaintsQueue: "Complaints",
    markResolved: "Mark resolved",
    resolved: "Resolved",
    open: "Open",
    shopContact: "Shop contact",
    inCharge: "In charge",
    updateHistory: "View update history",
    hideHistory: "Hide history",
    confirmAccurate: "Confirm accurate",
    confirmInaccurate: "Report inaccurate",
    confirmedBy: "confirmed by {n} of {m}",
    reportedBy: "Reported by",
    dateLabel: "Date",
    noComplaintsFound: "No complaints found.",
    shopkeeperDetails: "Shopkeeper details",
    taglineCommunity: "Stronger Communities",
    taglineTransparent: "Transparent Ration",
    taglineFair: "A Fairer Kerala",
    nearbyShopsSubtitle: "Find nearby ration shops and see live stock availability.",
    understandEntitlements: "Understand your entitlements",
    lowAccuracyLocation: "Location may be approximate",
    home: "Home",
    shopsFoundOne: "1 shop found",
    shopsFoundMany: "{n} shops found",
    shopsNearYouNote: "Showing ration shops near your location. Stock information is updated by the shopkeeper.",
    footerTagline: "A fairer Kerala through transparent ration distribution.",
    importantNote: "Important",
    disclaimerBullet1: "Entitlements and quantities are as per Government of Kerala regulations.",
    disclaimerBullet2: "Availability may vary by shop.",
    disclaimerBullet3: "Please refer to the latest orders for updates.",
    shopOpenNow: "Open now",
    shopClosedNow: "Closed",
  },
  ml: {
    appName: "റേഷൻലെൻസ്",
    citizen: "പൗരൻ",
    shopkeeper: "കടയുടമ",
    language: "ഭാഷ",
    findShop: "എന്റെ റേഷൻ കട കണ്ടെത്തുക",
    imShopkeeper: "ഞാൻ ഒരു കടയുടമയാണ്",
    landingTitle: "പോകുന്നതിന് മുമ്പ് സ്റ്റോക്ക് കാണുക",
    landingBody:
      "അടുത്തുള്ള റേഷൻ കടകളിലെ അരി, ഗോതമ്പ്, പഞ്ചസാര. അപ്‌ഡേറ്റ് കടയുടമയിൽ നിന്നാണ്, ഊഹത്തിൽ നിന്നല്ല.",
    searchPlaceholder: "ഇംഗ്ലീഷിലോ മലയാളത്തിലോ ചോദിക്കുക",
    search: "തിരയുക",
    voiceControls: "ശബ്ദ നിയന്ത്രണങ്ങൾ",
    voiceSearch: "ശബ്ദത്തിൽ ചോദിക്കുക",
    stopListening: "കേൾക്കുന്നത് നിർത്തുക",
    speakResults: "ഫലങ്ങൾ ശബ്ദത്തിൽ കേൾക്കുക",
    stopSpeaking: "വായന നിർത്തുക",
    voiceUnsupported: "ഈ ബ്രൗസറിൽ ശബ്ദ സൗകര്യം ലഭ്യമല്ല.",
    searchInterpreted: "തിരച്ചിൽ മനസ്സിലാക്കിയത്",
    shopSearch: "കട തിരച്ചിൽ",
    noMatchingStock: "പൊരുത്തപ്പെടുന്ന കടയോ സ്റ്റോക്കോ കണ്ടെത്തിയില്ല.",
    understood: "മനസ്സിലായി: അരി · അടുത്തുള്ളത്",
    list: "പട്ടിക",
    map: "ഭൂപടം",
    viewShop: "കട കാണുക",
    away: "ദൂരെ",
    findingLocation: "നിങ്ങളുടെ സ്ഥലം കണ്ടെത്തുന്നു…",
    approximateLocation: "ഏകദേശ സ്ഥലമാണ് ഉപയോഗിക്കുന്നത്.",
    tryAgain: "വീണ്ടും ശ്രമിക്കുക",
    dismiss: "ഒഴിവാക്കുക",
    getDirections: "വഴി കാണുക",
    notifyMe: "അറിയിക്കുക",
    notified: "നിങ്ങളെ അറിയിക്കും",
    notifications: "അറിയിപ്പുകൾ",
    noNotifications: "ഇതുവരെ അറിയിപ്പുകളില്ല",
    noHistory: "ചരിത്രമൊന്നുമില്ല",
    noNotificationsBody:
      "നിങ്ങൾ ചോദിച്ച സാധനം വന്നാൽ സന്ദേശം ഇവിടെ കാണാം.",
    login: "ലോഗിൻ",
    signup: "അക്കൗണ്ട് ഉണ്ടാക്കുക",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    name: "പേര്",
    role: "ഞാൻ ഒരു",
    assignedShop: "എന്റെ കട",
    loginError: "ഇമെയിലോ പാസ്‌വേഡോ ശരിയല്ല.",
    checkEmail: "അക്കൗണ്ട് സ്ഥിരീകരിക്കാൻ ഇമെയിൽ പരിശോധിക്കുക",
    nearbyShops: "അടുത്തുള്ള കടകൾ",
    shopNotFound: "ഈ കട പട്ടികയിലില്ല.",
    checkNumbers:
      "ഈ അക്കങ്ങൾ പരിശോധിക്കുക. തെറ്റുള്ളത് മാറ്റുക. നിങ്ങൾ സ്ഥിരീകരിക്കും വരെ സ്റ്റോക്ക് മാറില്ല.",
    choosePhoto:
      "സ്റ്റോക്ക് രജിസ്റ്ററിന്റെ ഫോട്ടോ തിരഞ്ഞെടുക്കുക. ലൈവാകുന്നതിന് മുമ്പ് അക്കങ്ങൾ തിരുത്താം.",
    showEmpty: "ശൂന്യമായ പട്ടിക കാണിക്കുക",
    showList: "മാതൃക സന്ദേശങ്ങൾ കാണിക്കുക",
    saveUpdate: "അപ്‌ഡേറ്റ് സേവ് ചെയ്യുക",
    stockSection: "നിലവിലെ സ്റ്റോക്ക്",
    saved: "സ്റ്റോക്ക് അപ്‌ഡേറ്റ് സേവ് ചെയ്തു.",
    history: "ചരിത്രം",
    viewRequests: "അഭ്യർത്ഥനകൾ കാണുക",
    noRequests: "ഇപ്പോൾ തീർച്ചപ്പെടുത്താത്ത അഭ്യർത്ഥനകളില്ല.",
    waiting: "കാത്തിരിക്കുന്നു",
    requested: "അഭ്യർത്ഥിച്ചത്",
    updatePhoto: "ഫോട്ടോ വഴി അപ്‌ഡേറ്റ്",
    manualUpdate: "സ്റ്റോക്ക് അപ്‌ഡേറ്റ്",
    quantity: "അളവ്",
    confirmPublish: "സ്ഥിരീകരിച്ച് പ്രസിദ്ധീകരിക്കുക",
    retake: "വീണ്ടും ഫോട്ടോ",
    enterManually: "തന്നെ നൽകുക",
    uploadImage: "ചിത്രം അപ്‌ലോഡ് ചെയ്യുക",
    weDetected: "കണ്ടെത്തിയത്",
    reading: "ചിത്രം വായിക്കുന്നു…",
    published: "പ്രസിദ്ധീകരിച്ചു. നിങ്ങൾ സ്ഥിരീകരിച്ചതിന് ശേഷം മാത്രം സ്റ്റോക്ക് മാറി.",
    back: "തിരികെ",
    rightsTitle: "നിങ്ങളുടെ അവകാശങ്ങൾ",
    rightsIntro: "നിങ്ങളുടെ പ്രതിമാസ അവകാശം കാണാൻ റേഷൻ കാർഡിന്റെ നിറം തിരഞ്ഞെടുക്കുക.",
    selectCardColor: "കാർഡ് നിറം തിരഞ്ഞെടുക്കുക",
    riceEntitlement: "അരി",
    wheatEntitlement: "ഗോതമ്പ് / ആട്ട",
    keroseneEntitlement: "മണ്ണെണ്ണ",
    readRights: "ഉറക്കെ വായിക്കുക",
    pendingVerificationTitle: "സ്ഥിരീകരണം കാത്തിരിക്കുന്നു",
    pendingVerificationBody: "നിങ്ങളുടെ കടയുടമ അക്കൗണ്ട് പരിശോധനയിലാണ്. ഒരു അഡ്മിൻ ഉടനെ ഇത് പരിശോധിക്കും.",
    rejectedTitle: "സ്ഥിരീകരണം നിരസിച്ചു",
    rejectedBody: "നിങ്ങളുടെ അപേക്ഷ അംഗീകരിച്ചില്ല. ദയവായി സപ്പോർട്ടുമായി ബന്ധപ്പെടുക.",
    licenseNumber: "FPS ലൈസൻസ് നമ്പർ",
    phoneNumber: "ഫോൺ നമ്പർ",
    uploadLicensePhoto: "നിങ്ങളുടെ കടയിലെ ലൈസൻസിന്റെ ഫോട്ടോ",
    applicationSubmitted: "നിങ്ങളുടെ അപേക്ഷ പരിശോധനയിലാണ്. അംഗീകരിച്ച ശേഷം നിങ്ങളെ അറിയിക്കും.",
    approve: "അംഗീകരിക്കുക",
    reject: "നിരസിക്കുക",
    adminShopkeeperQueue: "കടയുടമ ക്യൂ",
    logout: "ലോഗ്ഔട്ട്",
    shopkeeperQueueTitle: "കടയുടമ ക്യൂ",
    noPendingApplications: "തീർപ്പുകൽപ്പിക്കാത്ത കടയുടമ അപേക്ഷകൾ ഇല്ല.",
    phoneLabel: "ഫോൺ",
    licenseLabel: "ലൈസൻസ്",
    noProofImage: "തെളിവ് ചിത്രം നൽകിയിട്ടില്ല",
    assignShop: "കട നിയോഗിക്കുക",
    selectAShop: "ഒരു കട തിരഞ്ഞെടുക്കുക...",
    approvalFailed: "അംഗീകാരം പരാജയപ്പെട്ടു.",
    rejectionFailed: "നിരസിക്കൽ പരാജയപ്പെട്ടു.",
    confirmReject: "ഈ അപേക്ഷകനെ നിരസിക്കണമെന്ന് തീർച്ചയാണോ?",
    unknownName: "പേര് അജ്ഞാതം",
    noMalayalamVoice: "ഈ ഉപകരണത്തിൽ മലയാളം ശബ്ദം ലഭ്യമല്ല — മറ്റൊരു ബ്രൗസറോ ഉപകരണമോ ഉപയോഗിച്ച് നോക്കുക, അല്ലെങ്കിൽ ടെക്സ്റ്റ് നേരിട്ട് വായിക്കുക.",
    reportIssue: "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
    complaintCategory: "എന്താണ് പ്രശ്നം?",
    categoryOvercharging: "അധിക വില ഈടാക്കൽ",
    categoryWrongStock: "തെറ്റായ സ്റ്റോക്ക് വിവരം",
    categoryBehavior: "ജീവനക്കാരുടെ പെരുമാറ്റം",
    categoryOther: "മറ്റുള്ളവ",
    complaintDescription: "വിശദാംശങ്ങൾ ചേർക്കുക (ഓപ്ഷണൽ)",
    submitComplaint: "റിപ്പോർട്ട് സമർപ്പിക്കുക",
    complaintSubmitted: "നന്ദി. നിങ്ങളുടെ റിപ്പോർട്ട് അഡ്മിന് അയച്ചു.",
    adminComplaintsQueue: "പരാതികൾ",
    markResolved: "പരിഹരിച്ചതായി അടയാളപ്പെടുത്തുക",
    resolved: "പരിഹരിച്ചു",
    open: "തുറന്നത്",
    shopContact: "കടയുടെ ബന്ധപ്പെടേണ്ട വിവരം",
    inCharge: "ചുമതലയുള്ളയാൾ",
    updateHistory: "അപ്ഡേറ്റ് ചരിത്രം കാണുക",
    hideHistory: "ചരിത്രം മറയ്ക്കുക",
    confirmAccurate: "കൃത്യമാണെന്ന് സ്ഥിരീകരിക്കുക",
    confirmInaccurate: "കൃത്യമല്ലെന്ന് റിപ്പോർട്ട് ചെയ്യുക",
    confirmedBy: "{m} പേരിൽ {n} പേർ സ്ഥിരീകരിച്ചു",
    reportedBy: "റിപ്പോർട്ട് ചെയ്തത്",
    dateLabel: "തീയതി",
    noComplaintsFound: "പരാതികളൊന്നും കണ്ടെത്തിയില്ല.",
    shopkeeperDetails: "കടയുടമയുടെ വിവരങ്ങൾ",
    taglineCommunity: "ശക്തമായ സമൂഹങ്ങൾ",
    taglineTransparent: "സുതാര്യമായ റേഷൻ",
    taglineFair: "കൂടുതൽ നീതിയുള്ള കേരളം",
    nearbyShopsSubtitle: "അടുത്തുള്ള റേഷൻ കടകൾ കണ്ടെത്തി തത്സമയ സ്റ്റോക്ക് ലഭ്യത കാണുക.",
    understandEntitlements: "നിങ്ങളുടെ അവകാശങ്ങൾ മനസ്സിലാക്കുക",
    lowAccuracyLocation: "സ്ഥലം ഏകദേശമായിരിക്കാം",
    home: "ഹോം",
    shopsFoundOne: "1 കട കണ്ടെത്തി",
    shopsFoundMany: "{n} കടകൾ കണ്ടെത്തി",
    shopsNearYouNote: "നിങ്ങളുടെ സ്ഥലത്തിന് സമീപമുള്ള റേഷൻ കടകൾ കാണിക്കുന്നു. സ്റ്റോക്ക് വിവരങ്ങൾ കടയുടമ അപ്ഡേറ്റ് ചെയ്യുന്നു.",
    footerTagline: "സുതാര്യമായ റേഷൻ വിതരണത്തിലൂടെ കൂടുതൽ നീതിയുള്ള കേരളം.",
    importantNote: "പ്രധാനം",
    disclaimerBullet1: "അവകാശങ്ങളും അളവുകളും കേരള സർക്കാർ ചട്ടങ്ങൾ പ്രകാരമാണ്.",
    disclaimerBullet2: "ലഭ്യത കടയനുസരിച്ച് വ്യത്യാസപ്പെടാം.",
    disclaimerBullet3: "പുതുക്കിയ വിവരങ്ങൾക്ക് ഏറ്റവും പുതിയ ഉത്തരവുകൾ പരിശോധിക്കുക.",
    shopOpenNow: "ഇപ്പോൾ തുറന്നിരിക്കുന്നു",
    shopClosedNow: "അടച്ചിരിക്കുന്നു",
  },
} as const;
